### PR TITLE
Add Ant test target, run tests in Travis

### PR DESCRIPTION
**Pull request by richdougherty**
This PR allows the tests to be run from Ant. It then enables the tests as part of Travis validation. Some tests were failing so those have been marked with `@Ignore`.

### CODE REVIEW

**Comment by richdougherty** [comment]
Unfortunately I can't see the reason for the Travis build failure because Travis says "This is not an active repository". You may want to try re-activating the repo, see: http://stackoverflow.com/questions/32022899/seeing-this-is-not-an-active-repository-for-an-active-repository

**Comment by DavePearce** [comment]
Overall, it looks pretty good.  I like the use of <code>filelist</code> with <code>refid</code> --- not something I've done before.  I'll merge it in and we'll see how it looks.

I'm not sure what's going on with Travis.  To be honest, it seems to have problems with the WhileyCompiler repository because it's not associated with a user, but with an organisation :|

**Comment by DavePearce** [comment]
Hey,

Ok, building is now failing on my local machine.  The error message is:

<pre>
BUILD FAILED
/am/roxy/home/djp/projects/whiley/build.xml:2: The following error occurred while executing this line:
/am/roxy/home/djp/projects/whiley/config.xml:16: Unable to resolve artifact: Missing:
----------
1) junit:junit:jar:4.*

  Try downloading the file manually from the project website.
</pre>

This probably might be the same as on Travis.

**Comment by DavePearce** [comment]
Ok, looking at travis.  It's a bit wierd.  The corresponding build to the merge of this pull request is:

https://travis-ci.org/Whiley/WhileyCompiler/builds/103733846

But, there is no log reported?  It's just empty.  So, I've restarted the build to see if that has any effect.

**Comment by DavePearce** [comment]
Ok, no it still fails.  Hmmm, no output ... what does that mean?  Maybe the Travis log doesn't capture <code>stderr</code> ?

**Comment by DavePearce** [comment]
Ok, progress.  Local build is failing on my machine because missing proxy settings.

**Comment by DavePearce** [comment]
Hey Richard,

One thing: you need to sign the CONTRIBUTORS agreement as well.

D

**Comment by DavePearce** [comment]
Looks like Travis is having an upgrade or similar at the moment which is related to the log files.  Hence, that's probably why I can't see anything. See: https://twitter.com/traviscistatus

**Comment by DavePearce** [comment]
Really sorry for the all the comments on this!!  I think I've resolved the problem with Travis, as after a small tweak to the <code>.travis.yml</code> file after you updated it, the build is now passing again.  I just guessed what it might be.

https://github.com/Whiley/WhileyCompiler/commit/b5eb0a736efec4852ec7b35345ebac974c1420e9
https://travis-ci.org/Whiley/WhileyCompiler/builds/103745152

**Comment by richdougherty** [comment]
Travis can be a bit unstable sometimes! Glad to have my first bit of code merged in, even if it's just some build infrastructure. :)

Thanks for fixing the Travis script. I made another tweak: https://github.com/Whiley/WhileyCompiler/pull/572. I also added my name to the contributors file: https://github.com/Whiley/WhileyCompiler/pull/571

**Pull request merged**
