### PR TITLE
parameterized junit test cases

### LINKED ISSUE #580: Parameterised JUnit Tests
Would be great to automatically generate the JUnit tests directly from the test files, rather than maintaining a massive list of them.  One approach is:

https://github.com/junit-team/junit/wiki/Parameterized-tests

The main issue is how to manage the "ignored" tests as well, but there are certainly sensible solutions.  For example, could look for same named file with ".skip" extension.  Or, just read first line of test file and look for e.g. "// IGNORE".

### PR DESCRIPTION
**Pull request by SebastianS90**
Instead of listing all test cases in the junit file we can simply use one single `@Test` method that is parameterized and read the folder for available test cases.

As the `@Ignore` annotation is no longer usable in this setup, I introduced a static Map stating the name of a test case and the reason for ignoring it. I entered all test cases that used to have an `@Ignore` annotation into that map.

Furthermore, some test cases where not listed before and are failing, I added them to the ignore Map. The `While_Valid_7` test in `AllValidTests.java` was in the file before, but without `@Test` annotation such that it got silently ignored. As it fails I've added it to the ignore list, too.

Closes #580

### CODE REVIEW

**Comment by SebastianS90** [comment]
See also: https://github.com/junit-team/junit/wiki/Parameterized-tests

And we could get rid of the index in the `@Parameters(name = ...)` annotation, as the filename itself (in `{0}`) is unique and fully identifies the test.

**Comment by SebastianS90** [comment]
Travis [somehow failed](https://travis-ci.org/Whiley/WhileyCompiler/builds/108457951) but all tests succeed locally, therefore close+reopen to trigger [another run](https://travis-ci.org/Whiley/WhileyCompiler/builds/108462161).

**Comment by SebastianS90** [comment]
Again, not successful.
Travis:
````
    [junit] Running wyc.testing.AllInvalidTests
    [junit] Testsuite: wyc.testing.AllInvalidTests
    [junit] Tests run: 217, Failures: 0, Errors: 0, Time elapsed: 52.105 sec
    [junit] Tests run: 217, Failures: 0, Errors: 0, Time elapsed: 52.105 sec

    [junit] Running wyc.testing.AllValidTests
    [junit] Testsuite: wyc.testing.AllValidTests
    [junit] Testsuite: wyc.testing.AllValidTests
    [junit] Tests run: 1, Failures: 0, Errors: 1, Time elapsed: 0 sec
    [junit] 
    [junit] Testcase: valid[Byte_Valid_4] took 0.001 sec
    [junit] 	Caused an ERROR
    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
    [junit] Running wyc.testing.AllValidTests
    [junit] Tests run: 1, Failures: 0, Errors: 1, Time elapsed: 0 sec
    [junit] Test wyc.testing.AllValidTests FAILED (crashed)

    [junit] Running wyc.testing.AllValidVerificationTests
    [junit] Testsuite: wyc.testing.AllValidVerificationTests
    [junit] Tests run: 469, Failures: 0, Errors: 0, Time elapsed: 537.387 sec
    [junit] Tests run: 469, Failures: 0, Errors: 0, Time elapsed: 537.387 sec
````

Locally:
````
    [junit] Running wyc.testing.AllInvalidTests
    [junit] Testsuite: wyc.testing.AllInvalidTests
    [junit] Tests run: 217, Failures: 0, Errors: 0, Skipped: 62, Time elapsed: 9.423 sec
    [junit] Tests run: 217, Failures: 0, Errors: 0, Skipped: 62, Time elapsed: 9.423 sec

    [junit] Running wyc.testing.AllValidTests
    [junit] Testsuite: wyc.testing.AllValidTests
    [junit] Tests run: 469, Failures: 0, Errors: 0, Skipped: 36, Time elapsed: 83.675 sec
    [junit] Tests run: 469, Failures: 0, Errors: 0, Skipped: 36, Time elapsed: 83.675 sec

    [junit] Running wyc.testing.AllValidVerificationTests
    [junit] Testsuite: wyc.testing.AllValidVerificationTests
    [junit] Tests run: 469, Failures: 0, Errors: 0, Skipped: 131, Time elapsed: 162.263 sec
    [junit] Tests run: 469, Failures: 0, Errors: 0, Skipped: 131, Time elapsed: 162.263 sec
````

Please have a look at it @DavePearce 
Could be due to different versions of ant/java, a timeout or OutOfMemory on travis.
Locally I have `openjdk version "1.8.0_74"` and `Apache Ant(TM) version 1.9.6 compiled on July 3 2015`

**Comment by DavePearce** [comment]
Hey,

So, you're using Java 8.  Did you use any Java 8 specific features?  I might suggest setting the compiler level to 1.7, as Travis is configured only for openjdk7 at the moment.

**Comment by DavePearce** [comment]
Yeah, it's working fine for me locally as well.  I'm going merge the pull request and we can then figure out the Travis problem separately.

**Comment by DavePearce** [comment]
Done... thanks!

**Comment by SebastianS90** [comment]
Travis builds for further commits based on this here are running fine, so probably we got a bad runner three times in a row...

**Pull request merged**
